// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID          int64              `json:"id"`
	UserID      int32              `json:"user_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	UserID         int32  `json:"user_id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	Email          string `json:"email"`
}
